<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <IsTestProject>true</IsTestProject>
      <LangVersion>default</LangVersion>
      <AssemblyTitle>KitchenPC.UnitTests</AssemblyTitle>
      <Product>KitchenPC.UnitTests</Product>
      <Company>KitchenPC</Company>
      <OutputPath>bin\$(Configuration)\</OutputPath>
      <RootNamespace>KitchenPC.UnitTests</RootNamespace>
   </PropertyGroup>

   <ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.1" />
      <PackageReference Include="MSTest.TestAdapter" Version="3.0.2" />
      <PackageReference Include="MSTest.TestFramework" Version="3.0.2" />
   </ItemGroup>

   <ItemGroup>
      <ProjectReference Include="..\Core\Core.csproj" />
   </ItemGroup>

   <ItemGroup>
      <Content Include="ModelerData.xml">
         <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
   </ItemGroup>
</Project>
